### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

### ISSUE THREAD

**Issue by freeesty** [hypeserver/impferator#3]
https://www.doctolib.de/availabilities.json?start_date=2021-05-19&visit_motive_ids=2495719&agenda_ids=404654-457215-457244-397972-457210-457239-457213-457278-457283-457304-457306-457229-457234-457299-457212-457216-457288-457291-457315-457227-457204-457237-457296-397974-457312-457280-457206-457310-457319-397973-457243-457208-457218-457245-457274-457321&insurance_sector=public&practice_ids=158435&destroy_temporary=true&limit=4
Traceback (most recent call last):
  File "checkall.py", line 80, in <module>
    check()
  File "checkall.py", line 70, in check
    availability = requests.get(availability_url).json()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by yigitbey** [comment]
Doctolib started requiring user agent information, added that and it's working again @freeesty
